### ISSUE TITLE
Error running Demo app

### ISSUE THREAD

**Issue by tilllt** [z-x-yang/Segment-and-Track-Anything#112]
Hi,

i am getting this error running the demo app... also i had to install gradio manually, do i need to install a specific version?

```
/opt/conda/lib/python3.10/site-packages/gradio/layouts/column.py:55: UserWarning: 'scale' value should be an integer. Using 0.5 will cause issues.
  warnings.warn(
Traceback (most recent call last):
  File "/samta/app.py", line 1106, in <module>
    seg_track_app()
  File "/samta/app.py", line 485, in seg_track_app
    input_video = gr.Video(label='Input video').style(height=550)
AttributeError: 'Video' object has no attribute 'style'. Did you mean: 'scale'?
```

**Comment by yamy-cheng** [comment]
#113

**Comment by yamy-cheng** [comment]
Hi，use pip install gradio==3.38.0 to install gradio which support the code.
