### ISSUE TITLE
no module name "groundingdino"

### ISSUE THREAD

**Issue by cyandddd** [z-x-yang/Segment-and-Track-Anything#158]
The groundingdino is stopping me. I searched and the only relating issue is this https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/43#issuecomment-1502407150 . I tried his solution but it still does not work. Sorry I'm not a programmer so I do not know how to debug this. Please Help!

(venv) C:\Users\moloc\Segment-and-Track-Anything>python app.py

C:\Users\moloc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_client\documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
C:\Users\moloc\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_client\documentation.py:102: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")

Traceback (most recent call last):
  File "C:\Users\moloc\Segment-and-Track-Anything\app.py", line 11, in <module>
    from SegTracker import SegTracker
  File "C:\Users\moloc\Segment-and-Track-Anything\SegTracker.py", line 8, in <module>
    from tool.detector import Detector
  File "C:\Users\moloc\Segment-and-Track-Anything\tool\detector.py", line 6, in <module>
    from groundingdino.models import build_model as build_grounding_dino
ModuleNotFoundError: No module named 'groundingdino'

**Comment by amrzv** [comment]
Getting the same when running [colab](https://colab.research.google.com/drive/1R10N70AJaslzADFqb-a5OihYkllWEVxB?usp=sharing#scrollTo=TR7uVzWcH4s3). It happens due to installation error of `GroundingDINO`:
```python
Installing collected packages: pillow, GroundingDINO
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.2.0
    Uninstalling Pillow-9.2.0:
      Successfully uninstalled Pillow-9.2.0
  Running setup.py develop for GroundingDINO
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
