### ISSUE TITLE
'Image' object has no attribute 'select'

### ISSUE THREAD

**Issue by blueWall8** [z-x-yang/Segment-and-Track-Anything#25]
an error occurred while running app.py：
Traceback (most recent call last):
  File "E:\Segment-and-Track-Anything\app.py", line 674, in <module>
    seg_track_app()
  File "E:\Segment-and-Track-Anything\app.py", line 522, in seg_track_app
    input_first_frame.select(
AttributeError: 'Image' object has no attribute 'select'

**Comment by Bentonmaster** [comment]
hello,did you fix this?
