### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by HongliXiao** [z-x-yang/Segment-and-Track-Anything#3]
Hello, 我在运行 app.py 时遇到了以下报错，使用的是一块3070的显卡（8G），请问除了换更好的显卡之外还有什么办法解决吗，比如调小batch_size或num_workers，但是我没有在代码中找到相应的位置，可以帮我看一下该如何解决吗，非常感谢！

/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180487213/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
./aot/networks/layers/position.py:63: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_pos_feats)
Traceback (most recent call last): 0, obj_num 154
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/media/alienware/新加卷1/Research/Segment-and-Track-Anything-main/app.py", line 21, in predict
    return seg_track_anything(input_video_file, model, sam_gap, max_obj_num, points_per_side)
  File "/media/alienware/新加卷1/Research/Segment-and-Track-Anything-main/seg_track_anything.py", line 98, in seg_track_anything
    pred_mask = segtracker.track(frame,update_memory=True)
  File "/media/alienware/新加卷1/Research/Segment-and-Track-Anything-main/SegTracker.py", line 75, in track
    pred_mask = self.tracker.track(frame)
  File "/home/alienware/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/media/alienware/新加卷1/Research/Segment-and-Track-Anything-main/aot_tracker.py", line 79, in track
    pred_logit = self.engine.decode_current_logits((output_height, output_width))
  File "./aot/networks/engines/aot_engine.py", line 623, in decode_current_logits
    pred_id_logits = self.soft_logit_aggregation(all_logits)
  File "./aot/networks/engines/aot_engine.py", line 578, in soft_logit_aggregation
    merged_prob = torch.cat([bg_prob] + fg_probs,
RuntimeError: CUDA out of memory. Tried to allocate 1.24 GiB (GPU 0; 7.78 GiB total capacity; 4.38 GiB already allocated; 989.56 MiB free; 4.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by HongliXiao** [comment]
同样地，我在运行demo.ipynb的“Generate Results for the Whole Video”这一部分代码时，也遇到了同样的问题：

Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?532dd9e8-473d-499c-b5a6-7f7aaab99698)---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[15], line 52
     50     segtracker.add_reference(frame, pred_mask)
     51 else:
---> 52     pred_mask = segtracker.track(frame,update_memory=True)
     53 torch.cuda.empty_cache()
     54 gc.collect()

File [/media/alienware/](https://file+.vscode-resource.vscode-cdn.net/media/alienware/)新加卷1[/Research/Segment-and-Track-Anything-main/SegTracker.py:75](https://file+.vscode-resource.vscode-cdn.net/Research/Segment-and-Track-Anything-main/SegTracker.py:75), in SegTracker.track(self, frame, update_memory)
     67 def track(self,frame,update_memory=False):
     68     '''
     69     Track all known objects.
     70     Arguments:
   (...)
     73         merged_mask: numpy array (h,w)
     74     '''
---> 75     pred_mask = self.tracker.track(frame)
     76     if update_memory:
     77         self.tracker.update_memory(pred_mask)

File [~/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/torch/autograd/grad_mode.py:28](https://file+.vscode-resource.vscode-cdn.net/media/alienware/%E6%96%B0%E5%8A%A0%E5%8D%B71/Research/Segment-and-Track-Anything-main/~/anaconda3/envs/SAMTrack/lib/python3.9/site-packages/torch/autograd/grad_mode.py:28), in _DecoratorContextManager.__call__..decorate_context(*args, **kwargs)
     25 @functools.wraps(func)
     26 def decorate_context(*args, **kwargs):
     27     with self.__class__():
...
    579                         dim=1).clamp(1e-5, 1 - 1e-5)
    580 merged_logit = torch.logit(merged_prob)
    582 return merged_logit

RuntimeError: CUDA out of memory. Tried to allocate 1.09 GiB (GPU 0; 7.78 GiB total capacity; 5.02 GiB already allocated; 182.88 MiB free; 5.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by HongliXiao** [comment]
> 

感谢，我试着调整了一下这两个参数，可以多处理一些帧，但是仍旧无法；处理整个视频。我想问一下你们使用的显卡配置，看看能不能向老师申请换个好点的，谢谢！
