### ISSUE TITLE
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).

### ISSUE THREAD

**Issue by hansgreen4396** [z-x-yang/Segment-and-Track-Anything#51]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mwx\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Anaconda3\envs\mwx\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\Anaconda3\envs\mwx\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Anaconda3\envs\mwx\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Anaconda3\envs\mwx\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Anaconda3\envs\mwx\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:/mwx/Segment-and-Track-Anything/app.py", line 251, in tracking_objects
    return tracking_objects_in_video(Seg_Tracker, input_video, input_img_seq, fps)
  File "E:\mwx\Segment-and-Track-Anything\seg_track_anything.py", line 94, in tracking_objects_in_video
    return video_type_input_tracking(SegTracker, input_video, io_args, video_name)
  File "E:\mwx\Segment-and-Track-Anything\seg_track_anything.py", line 196, in video_type_input_tracking
    imageio.mimsave(io_args['output_gif'], masked_pred_list, fps=fps)
  File "D:\Anaconda3\envs\mwx\lib\site-packages\imageio\v2.py", line 484, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "D:\Anaconda3\envs\mwx\lib\site-packages\imageio\plugins\pillow.py", line 354, in write
    raise TypeError(
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).

**Comment by Ammar-hala** [comment]
Inside file seg_track_anything.py , at line 196 and line 288.

Replace " **imageio.mimsave(io_args['output_gif'], masked_pred_list, fps=fps)** " with     " **imageio.mimsave(io_args['output_gif'], masked_pred_list, duration=1000/fps)** "
