### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by Qingqingniu** [z-x-yang/Segment-and-Track-Anything#6]
Thank you for your great work, but when run demo.py, I meet a problem like this:
Object number: 44. Inference size: 577x1041. Output size: 1080x1920.
./anaconda3/envs/seg/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755853042/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
./aot/networks/layers/position.py:64: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_pos_feats)
Traceback (most recent call last):
  File "./aot/tools/demo.py", line 338, in <module>
    main()
  File "./aot/tools/demo.py", line 283, in main
    demo(cfg)
  File "./aot/tools/demo.py", line 202, in demo
    engine.add_reference_frame(current_img,
  File "./aot/networks/engines/aot_engine.py", line 601, in add_reference_frame
    aot_engine.add_reference_frame(img,
  File "./aot/networks/engines/aot_engine.py", line 234, in add_reference_frame
    self.curr_lstt_output = self.AOT.LSTT_forward(curr_enc_embs,
  File "./aot/networks/models/aot.py", line 103, in LSTT_forward
    lstt_embs, lstt_memories = self.LSTT(curr_emb, long_term_memories,
  File "./anaconda3/envs/seg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "./aot/networks/layers/transformer.py", line 106, in forward
    output, memories = layer(output,
  File "./anaconda3/envs/seg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "./aot/networks/layers/transformer.py", line 342, in forward
    tgt3 = self.short_term_attn(local_Q, local_K, local_V)[0]
  File "./anaconda3/envs/seg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "./aot/networks/layers/attention.py", line 354, in forward
    qk = qk + relative_emb
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)
Could you help me solve this problem, thanks a lot !

**Comment by Qingqingniu** [comment]
> What‘s your environment？We recommend pytorch 1.10 for running the project.

The PyTorch version in my environment is 1.11.0, do I need to downgrade PyTorch?

**Comment by z-x-yang** [comment]
Install pytorch correlation from the source may solve the problem:
```
git clone https://github.com/ClementPinard/Pytorch-Correlation-extension.git
cd Pytorch-Correlation-extension; python setup.py install
```
